"""
Mazegen Module
==============
Standalone reusable module for maze generation using DFS.

Classes:
    Settings: validates and stores a maze configuration
    MazeGenerator: maze generation, renderer and pathfinding logic

Quick Start
-----------
Instantiate a Settings object and pass it to MazeGenerator,
then call generate():

    from mazegen import Settings, MazeGenerator

    settings = Settings(
        WIDTH=15,
        HEIGHT=10,
        ENTRY=(0, 0),
        EXIT=(14, 9),
        OUTPUT_FILE="maze.txt",
        PERFECT=True,
        SEED=42
    )

    gen = MazeGenerator(settings)
    gen.generate()

Custom Parameters
-----------------
- WIDTH / HEIGHT (int, 3-40): dimensions of the maze grid.
- ENTRY / EXIT (tuple[int, int]): (x, y) coordinates of
  the start and end cells.
- PERFECT (bool): True for a perfect maze (no loops);
  False adds extra passages.
- SEED (int | None): fixed seed for reproducible results; None for random.
- OUTPUT_FILE (str): filename for the saved output (e.g. "maze.txt").

Accessing the Maze Structure
----------------------------
After calling generate(), the maze is available as::

    gen.grid  # list[list[int]] - each cell encodes open walls as bitmask
              # Bit 0 (0x1) = NORTH wall present
              # Bit 1 (0x2) = EAST  wall present
              # Bit 2 (0x4) = SOUTH wall present
              # Bit 3 (0x8) = WEST  wall present
              # 0 means all four walls are open

Accessing the Solution
----------------------
The solution path is written to the output file generated by save_maze().
The file contains the raw grid, followed by the ENTRY and EXIT coordinates
and a "Pathfinder" marker that is a placeholder for the future pathfinding:

    # Read the output file after generation:
    with open("Output_maze.txt") as f:
        print(f.read())
"""
from __future__ import annotations
from string import ascii_letters
from random import Random
from sys import exit
try:
    from pydantic import (
        BaseModel,
        Field,
        field_validator,
        model_validator)
except ImportError as error:
    print(error)
    exit(1)


class Settings(BaseModel):
    """Pydantic model that validates and stores the maze configuration."""
    WIDTH: int = Field(ge=3, le=40)
    HEIGHT: int = Field(ge=3, le=40)
    ENTRY: tuple[int, int]
    EXIT: tuple[int, int]
    OUTPUT_FILE: str
    PERFECT: bool
    SEED: int | None = None

    @field_validator('ENTRY', 'EXIT', mode="before")
    @classmethod
    def parse_tuple(cls, value: str) -> tuple[int, int]:
        """Parses a string like '(x, y)' into a tuple of two ints.
           Called automatically by Pydantic."""
        clean = value.strip(ascii_letters + '() ')
        x, y = clean.split(",")
        return (int(x.strip()), int(y.strip()))

    @field_validator('OUTPUT_FILE', mode="after")
    @classmethod
    def validator_output_file(cls, name: str) -> str:
        """Validates that the output file name is non-empty,
           starts with a letter, and ends with '.txt'.
           Called automatically by Pydantic."""
        _name = name.removesuffix('.txt')
        if not _name:
            raise ValueError("Output file name cannot be empty")
        if not _name[0].isalpha():
            raise ValueError(f"Output file must start with a letter: '{name}'")
        if not all(c.isalnum() or c in '_-' for c in _name):
            raise ValueError(f"Invalid output file name: '{name}'\n"
                             "Allowed: letters, numbers, _ and -")
        if not name.endswith('.txt'):
            raise ValueError(f'Incorrect output_file: {name}:\n'
                             'valid example: maze.txt')
        else:
            return name

    @model_validator(mode='after')
    def validator_maze(self) -> Settings:
        """Validates that entry/exit are within bounds
           and do not overlap with the '42' pattern.
           Called automatically by Pydantic."""
        entry_x, entry_y = self.ENTRY
        exit_x, exit_y = self.EXIT
        if entry_x >= self.WIDTH or exit_x >= self.WIDTH:
            raise ValueError('Coordinates cannot exceed Width')
        if entry_y >= self.HEIGHT or exit_y >= self.HEIGHT:
            raise ValueError('Coordinates cannot exceed Height')
        if any(c < 0 for c in (*self.ENTRY, *self.EXIT)):
            raise ValueError('Coordinates cannot be negative')
        if self.ENTRY == self.EXIT:
            raise ValueError('Entry and Exit cannot be the same cell')

        fixed = MazeGenerator._compute_fixed_cells(self.WIDTH, self.HEIGHT)
        for label, coord in (("Entry", self.ENTRY), ("Exit", self.EXIT)):
            if coord in fixed:
                raise ValueError(
                    f"{label} {coord} overlaps with the '42' pattern")
        return self

    def show_settings(self) -> None:
        """Prints the current settings to stdout.
           Usage: settings.show_settings()"""
        print("\n    ===== Settings ===== \n"
              f"\n    Width: {self.WIDTH}\n"
              f"    Height: {self.HEIGHT}\n"
              f"    Entry: {self.ENTRY}\n    Exit: {self.EXIT}\n"
              f"\n    Output_file: {self.OUTPUT_FILE}\n"
              f"    Perfect: {self.PERFECT}\n"
              f"    Seed: {self.SEED}\n"
              f"    {20 * '-'}")


class MazeGenerator:
    """
    Generates a maze using a Depth-First Search (DFS) algorithm.

    Attributes:
        grid (list[list[int]] | None): the maze grid after generate().
            Each cell is an integer bitmask encoding which walls are present.
        fixed (set[tuple[int, int]]): cells that are blocked ('42' pattern).
        ENTRY (tuple[int, int]): start cell coordinates (x, y).
        EXIT  (tuple[int, int]): end cell coordinates (x, y).
    """
    def __init__(self, settings: Settings) -> None:
        self.settings: Settings = settings
        self.WIDTH: int = settings.WIDTH
        self.HEIGHT: int = settings.HEIGHT
        self.ENTRY: tuple[int, int] = settings.ENTRY
        self.EXIT: tuple[int, int] = settings.EXIT
        self.OUTPUT_FILE: str = settings.OUTPUT_FILE
        self.PERFECT: bool = settings.PERFECT
        self.SEED: int | None = settings.SEED
        self.grid: list[list[int]] | None = None
        self.fixed: set[tuple[int, int]] = set()

    @staticmethod
    def _compute_fixed_cells(
            width: int, height: int) -> set[tuple[int, int]]:
        """Returns the set of fixed cells for the '42' pattern,
           or an empty set if the maze is too small."""
        pattern_w = 7
        pattern_h = 5
        four = [
            [1, 0, 1],
            [1, 0, 1],
            [1, 1, 1],
            [0, 0, 1],
            [0, 0, 1],
        ]
        two = [
            [1, 1, 1],
            [0, 0, 1],
            [1, 1, 1],
            [1, 0, 0],
            [1, 1, 1],
        ]
        fixed: set[tuple[int, int]] = set()
        if width >= pattern_w + 2 and height >= pattern_h + 2:
            start_x = (width - pattern_w) // 2
            start_y = (height - pattern_h) // 2
            for row in range(pattern_h):
                for col in range(3):
                    if four[row][col]:
                        fixed.add((start_x + col, start_y + row))
                    if two[row][col]:
                        fixed.add((start_x + 4 + col, start_y + row))
        return fixed

    def show_maze(self) -> None:
        """Prints the grid as hex values to stdout.
           Usage: gen.show_maze()"""
        if self.grid is None:
            raise ValueError("Generate a maze first")
        grid: list[list[int]] = self.grid
        print("Generated maze:\n")
        print('\n'.join(
             ''.join(format(cell, 'X') for cell in row)
             for row in grid)
        )
        print()

    def save_maze(self) -> None:
        """Saves the maze grid and metadata to the output file.
           Usage: gen.save_maze()"""
        if self.grid is None:
            raise ValueError("Generate a maze first")
        with open("Output_" + self.settings.OUTPUT_FILE, 'w') as f:
            for row in self.grid:
                f.write(''.join(format(cell, 'X') for cell in row) + '\n')
            f.write('\n')
            f.write(f'{self.ENTRY}\n')
            f.write(f'{self.EXIT}\n')
            f.write("Pathfinder\n")

    def generate(self) -> None:
        """Generates the maze using DFS and saves it to the output file.
           Usage: gen.generate()"""
        NORTH = 0x1
        EAST = 0x2
        SOUTH = 0x4
        WEST = 0x8

        DIRECTIONS = {
            NORTH: (0, -1),
            EAST:  (1,  0),
            SOUTH: (0,  1),
            WEST:  (-1, 0)}

        OPPOSITE = {
            NORTH: SOUTH,
            SOUTH: NORTH,
            EAST:  WEST,
            WEST:  EAST}

        rng = Random(self.SEED)

        # Fixed cells if the maze is large enough (min 9x7)
        self.fixed = self._compute_fixed_cells(self.WIDTH, self.HEIGHT)
        if not self.fixed:
            print("Note: Maze too small for the '42' pattern, omitting it.")

        # 1. Start: Fill grid with 0xF
        self.grid = [
            [0xF] * self.WIDTH for _ in range(self.HEIGHT)]

        # 2. DFS — fixed cells are pre-visited so DFS never carves them
        visited: set[tuple[int, int]] = set(self.fixed)
        stack: list[tuple[int, int]] = [self.ENTRY]
        visited.add(self.ENTRY)

        while stack:
            x, y = stack[-1]
            dirs = list(DIRECTIONS.keys())
            rng.shuffle(dirs)
            carved = False
            for direction in dirs:
                dx, dy = DIRECTIONS[direction]
                nx, ny = x + dx, y + dy
                if 0 <= nx < self.WIDTH and 0 <= ny < self.HEIGHT:
                    if (nx, ny) not in visited:
                        self.grid[y][x] &= ~direction
                        self.grid[ny][nx] &= ~OPPOSITE[direction]
                        visited.add((nx, ny))
                        stack.append((nx, ny))
                        carved = True
                        break
            if not carved:
                stack.pop()

        # 3. If perfect=false, remove extra walls (skip fixed cells)
        if not self.PERFECT:
            for _ in range(self.WIDTH * self.HEIGHT // 4):
                x = rng.randint(0, self.WIDTH - 2)
                y = rng.randint(0, self.HEIGHT - 2)
                direction = rng.choice([EAST, SOUTH])
                dx, dy = DIRECTIONS[direction]
                nx, ny = x + dx, y + dy
                if (x, y) not in self.fixed and (nx, ny) not in self.fixed:
                    self.grid[y][x] &= ~direction
                    self.grid[ny][nx] &= ~OPPOSITE[direction]
        self.save_maze()

    def render_maze(self, color: str) -> None:
        """Renders the maze to the terminal with optional color.
           Usage: gen.render_maze('blue') Only white and blue available"""
        if self.grid is None:
            return

        NORTH = 0x1
        WEST = 0x8

        RESET = "\033[0m"
        YELLOW_BG = "\033[43m"
        MAIN = "\033[94m" if color == "blue" else ""

        grid = self.grid
        height = len(grid)
        width = len(grid[0]) if height > 0 else 0
        fixed = self.fixed

        output = []

        for y in range(height):
            # Top wall row
            top = MAIN
            for x in range(width):
                cell = grid[y][x]
                top += "+" + ("---" if (cell & NORTH) else "   ")
            output.append(top + "+" + (RESET if MAIN else ""))

            # Cell row with left walls
            mid = ""
            for x in range(width):
                cell = grid[y][x]
                wall = MAIN + ("|" if (cell & WEST) else " ") + RESET
                if (x, y) in fixed:
                    interior = YELLOW_BG + "   " + RESET
                elif (x, y) == self.ENTRY:
                    interior = MAIN + " S " + (RESET if MAIN else "")
                elif (x, y) == self.EXIT:
                    interior = MAIN + " E " + (RESET if MAIN else "")
                else:
                    interior = MAIN + "   " + (RESET if MAIN else "")
                mid += wall + interior
            output.append(mid + MAIN + "|" + (RESET if MAIN else ""))

        # Bottom border
        output.append(MAIN + "+" + "---+" * width + (RESET if MAIN else ""))

        print()
        print('\n'.join(output))
        print()
